language: r
sudo: required

services:
  - mysql
  - postgresql

r_github_packages:
  - jimhester/lintr

# Set test databases with travis CLI command deal with braces and quoting
# env:
  # DBEZR_TEST_MYSQL '[{"user":"root", "password":"", "host":"127.0.0.1", "dbname":"dbezr", "engine": "MySQL" }]'
  # DBEZR_TEST_POSTGRES '[{"user": "postgres", "password": "", "host": "127.0.0.1", "dbname": "travis_ci_test", "engine": "PostgreSQL"}]'

before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  - Rscript -e 'lintr::lint_package()'
